import { api, listAll } from "./client";
import type {
  Amortissement,
  AnomalieDetectee,
  Article,
  ArticleFournisseur,
  Avoir,
  BesoinApprovisionnement,
  BesoinMatierePrevu,
  BonLivraison,
  Caisse,
  Chauffeur,
  Client,
  Cloture,
  CodeFiscal,
  FamilleArticle,
  FamilleFiscale,
  FormatArticle,
  Parfum,
  UniteVenteArticle,
  Commande,
  CommandeFournisseur,
  CompositionFicheTechnique,
  ContratClient,
  ContratFournisseur,
  ControleQualite,
  ControleQualiteRequis,
  ControleRetour,
  CoutEnergie,
  CoutMatiere,
  CoutMainOeuvre,
  CoutReel,
  CoutRetourPerte,
  CoutStandard,
  Decaissement,
  DemandeAchat,
  DemandeComplementaire,
  DemandeMatiere,
  Depot,
  DepotDistribution,
  EcartCaisse,
  Encaissement,
  EtapeProduction,
  ExportComptable,
  Facture,
  FicheConditionnement,
  FicheTechnique,
  Fournisseur,
  Inventaire,
  JournalAction,
  LigneCommande,
  LigneCommandeFournisseur,
  LigneFacture,
  LigneInventaire,
  LigneReceptionAchat,
  Lot,
  MouvementStock,
  OrdreFabrication,
  PerteProduction,
  PlanProduction,
  PreparationLivraison,
  Profil,
  Prospect,
  RapportGenere,
  ReceptionAchat,
  ReclamationClient,
  Reconditionnement,
  RetourFournisseur,
  RetourMatiere,
  RetourPhysique,
  SessionCaisse,
  SolutionClient,
  SortieMatiere,
  StockArticle,
  SuiviEau,
  SuiviProduction,
  Tarif,
  Tournee,
  TransfertDepot,
  Utilisateur,
  Vehicule,
} from "../types";

export const endpoints = {
  utilisateurs: "/comptes/utilisateurs/",
  journal: "/comptes/journal/",
  articles: "/referentiel/articles/",
  controlesQualiteRequis: "/referentiel/controles-qualite-requis/",
  codesFiscaux: "/fiscalite/codes-fiscaux/",
  famillesFiscales: "/fiscalite/familles-fiscales/",
  famillesArticle: "/referentiel/familles/",
  formatsArticle: "/referentiel/formats/",
  parfums: "/referentiel/parfums/",
  unitesVente: "/referentiel/unites-vente/",
  fichesTechniques: "/referentiel/fiches-techniques/",
  compositions: "/referentiel/compositions/",
  fichesConditionnement: "/referentiel/fiches-conditionnement/",
  fournisseurs: "/achats/fournisseurs/",
  contratsFournisseurs: "/achats/contrats-fournisseurs/",
  catalogueFournisseurs: "/achats/catalogue-fournisseurs/",
  besoinsAchat: "/achats/besoins/",
  demandesAchat: "/achats/demandes/",
  commandesFournisseur: "/achats/commandes/",
  lignesCommandeFournisseur: "/achats/lignes-commande/",
  receptions: "/achats/receptions/",
  lignesReception: "/achats/lignes-reception/",
  retoursFournisseur: "/achats/retours/",
  depots: "/stocks/depots/",
  stock: "/stocks/stock-articles/",
  mouvements: "/stocks/mouvements/",
  inventaires: "/stocks/inventaires/",
  lignesInventaire: "/stocks/lignes-inventaire/",
  plans: "/production/plans/",
  ofList: "/production/ordres-fabrication/",
  besoinsMatieres: "/production/besoins-matieres/",
  demandesMatieres: "/production/demandes-matieres/",
  demandesComplementaires: "/production/demandes-complementaires/",
  sortiesMatieres: "/production/sorties-matieres/",
  retoursMatieres: "/production/retours-matieres/",
  suivisProduction: "/production/suivis-production/",
  suivisEau: "/production/suivis-eau/",
  etapes: "/production/etapes/",
  pertes: "/production/pertes/",
  lots: "/qualite/lots/",
  controles: "/qualite/controles/",
  clients: "/commercial/clients/",
  prospects: "/commercial/prospects/",
  contratsClients: "/commercial/contrats/",
  tarifs: "/commercial/tarifs/",
  commandes: "/commercial/commandes/",
  lignesCommande: "/commercial/lignes-commande/",
  factures: "/commercial/factures/",
  lignesFacture: "/commercial/lignes-facture/",
  avoirs: "/commercial/avoirs/",
  caisses: "/caisse/caisses/",
  sessionsCaisse: "/caisse/sessions/",
  encaissements: "/caisse/encaissements/",
  decaissements: "/caisse/decaissements/",
  ecartsCaisse: "/caisse/ecarts/",
  vehicules: "/distribution/vehicules/",
  chauffeurs: "/distribution/chauffeurs/",
  depotsDistribution: "/distribution/depots/",
  tournees: "/distribution/tournees/",
  preparations: "/distribution/preparations/",
  bonsLivraison: "/distribution/bons-livraison/",
  transferts: "/distribution/transferts/",
  reclamations: "/reclamations/reclamations/",
  retoursPhysiques: "/reclamations/retours-physiques/",
  controlesRetour: "/reclamations/controles/",
  reconditionnements: "/reclamations/reconditionnements/",
  coutsRetours: "/reclamations/couts-retours/",
  solutionsReclamation: "/reclamations/solutions/",
  coutsMatieres: "/couts/couts-matieres/",
  coutsEnergie: "/couts/couts-energie/",
  coutsMainOeuvre: "/couts/couts-main-oeuvre/",
  amortissements: "/couts/amortissements/",
  coutsStandards: "/couts/couts-standards/",
  coutsReels: "/couts/couts-reels/",
  anomalies: "/comptabilite/anomalies/",
  exportsComptables: "/comptabilite/exports/",
  clotures: "/comptabilite/clotures/",
  rapports: "/reporting/rapports/",
} as const;

export type EndpointKey = keyof typeof endpoints;

export const catalog = {
  utilisateurs: () => listAll<Utilisateur>(endpoints.utilisateurs),
  journal: () => listAll<JournalAction>(endpoints.journal),
  articles: () => listAll<Article>(endpoints.articles),
  controlesQualiteRequis: () => listAll<ControleQualiteRequis>(endpoints.controlesQualiteRequis),
  codesFiscaux: () => listAll<CodeFiscal>(endpoints.codesFiscaux),
  famillesFiscales: () => listAll<FamilleFiscale>(endpoints.famillesFiscales),
  famillesArticle: () => listAll<FamilleArticle>(endpoints.famillesArticle),
  formatsArticle: () => listAll<FormatArticle>(endpoints.formatsArticle),
  parfums: () => listAll<Parfum>(endpoints.parfums),
  unitesVente: () => listAll<UniteVenteArticle>(endpoints.unitesVente),
  fichesTechniques: () => listAll<FicheTechnique>(endpoints.fichesTechniques),
  compositions: () => listAll<CompositionFicheTechnique>(endpoints.compositions),
  fichesConditionnement: () => listAll<FicheConditionnement>(endpoints.fichesConditionnement),
  fournisseurs: () => listAll<Fournisseur>(endpoints.fournisseurs),
  contratsFournisseurs: () => listAll<ContratFournisseur>(endpoints.contratsFournisseurs),
  catalogueFournisseurs: () => listAll<ArticleFournisseur>(endpoints.catalogueFournisseurs),
  besoinsAchat: () => listAll<BesoinApprovisionnement>(endpoints.besoinsAchat),
  demandesAchat: () => listAll<DemandeAchat>(endpoints.demandesAchat),
  commandesFournisseur: () => listAll<CommandeFournisseur>(endpoints.commandesFournisseur),
  lignesCommandeFournisseur: () => listAll<LigneCommandeFournisseur>(endpoints.lignesCommandeFournisseur),
  receptions: () => listAll<ReceptionAchat>(endpoints.receptions),
  lignesReception: () => listAll<LigneReceptionAchat>(endpoints.lignesReception),
  retoursFournisseur: () => listAll<RetourFournisseur>(endpoints.retoursFournisseur),
  depots: () => listAll<Depot>(endpoints.depots),
  stock: () => listAll<StockArticle>(endpoints.stock),
  mouvements: () => listAll<MouvementStock>(endpoints.mouvements),
  inventaires: () => listAll<Inventaire>(endpoints.inventaires),
  lignesInventaire: () => listAll<LigneInventaire>(endpoints.lignesInventaire),
  plans: () => listAll<PlanProduction>(endpoints.plans),
  ofList: () => listAll<OrdreFabrication>(endpoints.ofList),
  besoinsMatieres: () => listAll<BesoinMatierePrevu>(endpoints.besoinsMatieres),
  demandesMatieres: () => listAll<DemandeMatiere>(endpoints.demandesMatieres),
  demandesComplementaires: () => listAll<DemandeComplementaire>(endpoints.demandesComplementaires),
  sortiesMatieres: () => listAll<SortieMatiere>(endpoints.sortiesMatieres),
  retoursMatieres: () => listAll<RetourMatiere>(endpoints.retoursMatieres),
  suivisProduction: () => listAll<SuiviProduction>(endpoints.suivisProduction),
  suivisEau: () => listAll<SuiviEau>(endpoints.suivisEau),
  etapes: () => listAll<EtapeProduction>(endpoints.etapes),
  pertes: () => listAll<PerteProduction>(endpoints.pertes),
  lots: () => listAll<Lot>(endpoints.lots),
  controles: () => listAll<ControleQualite>(endpoints.controles),
  clients: () => listAll<Client>(endpoints.clients),
  prospects: () => listAll<Prospect>(endpoints.prospects),
  contratsClients: () => listAll<ContratClient>(endpoints.contratsClients),
  tarifs: () => listAll<Tarif>(endpoints.tarifs),
  commandes: () => listAll<Commande>(endpoints.commandes),
  lignesCommande: () => listAll<LigneCommande>(endpoints.lignesCommande),
  factures: () => listAll<Facture>(endpoints.factures),
  lignesFacture: () => listAll<LigneFacture>(endpoints.lignesFacture),
  avoirs: () => listAll<Avoir>(endpoints.avoirs),
  caisses: () => listAll<Caisse>(endpoints.caisses),
  sessionsCaisse: () => listAll<SessionCaisse>(endpoints.sessionsCaisse),
  encaissements: () => listAll<Encaissement>(endpoints.encaissements),
  decaissements: () => listAll<Decaissement>(endpoints.decaissements),
  ecartsCaisse: () => listAll<EcartCaisse>(endpoints.ecartsCaisse),
  vehicules: () => listAll<Vehicule>(endpoints.vehicules),
  chauffeurs: () => listAll<Chauffeur>(endpoints.chauffeurs),
  depotsDistribution: () => listAll<DepotDistribution>(endpoints.depotsDistribution),
  tournees: () => listAll<Tournee>(endpoints.tournees),
  preparations: () => listAll<PreparationLivraison>(endpoints.preparations),
  bonsLivraison: () => listAll<BonLivraison>(endpoints.bonsLivraison),
  transferts: () => listAll<TransfertDepot>(endpoints.transferts),
  reclamations: () => listAll<ReclamationClient>(endpoints.reclamations),
  retoursPhysiques: () => listAll<RetourPhysique>(endpoints.retoursPhysiques),
  controlesRetour: () => listAll<ControleRetour>(endpoints.controlesRetour),
  reconditionnements: () => listAll<Reconditionnement>(endpoints.reconditionnements),
  coutsRetours: () => listAll<CoutRetourPerte>(endpoints.coutsRetours),
  solutionsReclamation: () => listAll<SolutionClient>(endpoints.solutionsReclamation),
  coutsMatieres: () => listAll<CoutMatiere>(endpoints.coutsMatieres),
  coutsEnergie: () => listAll<CoutEnergie>(endpoints.coutsEnergie),
  coutsMainOeuvre: () => listAll<CoutMainOeuvre>(endpoints.coutsMainOeuvre),
  amortissements: () => listAll<Amortissement>(endpoints.amortissements),
  coutsStandards: () => listAll<CoutStandard>(endpoints.coutsStandards),
  coutsReels: () => listAll<CoutReel>(endpoints.coutsReels),
  anomalies: () => listAll<AnomalieDetectee>(endpoints.anomalies),
  exportsComptables: () => listAll<ExportComptable>(endpoints.exportsComptables),
  clotures: () => listAll<Cloture>(endpoints.clotures),
  rapports: () => listAll<RapportGenere>(endpoints.rapports),
};

export type CatalogKey = keyof typeof catalog;

const SHARED_CATALOG: CatalogKey[] = ["articles", "stock", "lots"];

const CATALOG_BY_ROLE: Record<Profil, CatalogKey[]> = {
  ADMIN_SI: Object.keys(catalog) as CatalogKey[],
  DIRECTION: [
    "articles",
    "stock",
    "lots",
    "journal",
    "ofList",
    "encaissements",
    "coutsMatieres",
    "coutsEnergie",
    "coutsMainOeuvre",
    "amortissements",
    "coutsStandards",
    "coutsReels",
    "anomalies",
    "rapports",
  ],
  RESPONSABLE_PRODUCTION: [
    "codesFiscaux",
    "famillesFiscales",
    "famillesArticle",
    "formatsArticle",
    "parfums",
    "unitesVente",
    "articles",
    "fichesTechniques",
    "compositions",
    "fichesConditionnement",
    "plans",
    "ofList",
    "besoinsMatieres",
    "demandesMatieres",
    "demandesComplementaires",
    "sortiesMatieres",
    "retoursMatieres",
    "suivisProduction",
    "suivisEau",
    "etapes",
    "pertes",
    "stock",
    "lots",
    "depots",
    "demandesAchat",
    "besoinsAchat",
  ],
  AGENT_PRODUCTION: [
    "famillesArticle",
    "articles",
    "ofList",
    "demandesComplementaires",
    "suivisProduction",
    "suivisEau",
    "etapes",
    "pertes",
    "stock",
    "lots",
  ],
  RESPONSABLE_QUALITE: [
    "codesFiscaux",
    "famillesFiscales",
    "famillesArticle",
    "formatsArticle",
    "parfums",
    "unitesVente",
    "articles",
    "lots",
    "controles",
    "controlesQualiteRequis",
    "controlesRetour",
    "retoursPhysiques",
    "stock",
    "fichesTechniques",
    "ofList",
  ],
  MAGASINIER: [
    "articles",
    "depots",
    "stock",
    "mouvements",
    "inventaires",
    "lignesInventaire",
    "sortiesMatieres",
    "retoursMatieres",
    "besoinsMatieres",
    "demandesMatieres",
    "demandesComplementaires",
    "receptions",
    "lignesReception",
    "demandesAchat",
    "commandesFournisseur",
    "lignesCommandeFournisseur",
    "preparations",
    "commandes",
    "lots",
    "transferts",
  ],
  RESPONSABLE_ACHATS: [
    "codesFiscaux",
    "famillesFiscales",
    "famillesArticle",
    "formatsArticle",
    "parfums",
    "unitesVente",
    "articles",
    "fournisseurs",
    "contratsFournisseurs",
    "catalogueFournisseurs",
    "besoinsAchat",
    "demandesAchat",
    "commandesFournisseur",
    "lignesCommandeFournisseur",
    "receptions",
    "lignesReception",
    "stock",
    "lots",
  ],
  COMMERCIAL: [
    "famillesFiscales",
    "famillesArticle",
    "formatsArticle",
    "parfums",
    "unitesVente",
    "articles",
    "codesFiscaux",
    "stock",
    "lots",
    "clients",
    "prospects",
    "contratsClients",
    "tarifs",
    "commandes",
    "lignesCommande",
    "factures",
    "lignesFacture",
    "avoirs",
    "reclamations",
  ],
  CAISSIER: [
    "articles",
    "commandes",
    "factures",
    "caisses",
    "sessionsCaisse",
    "encaissements",
    "decaissements",
    "ecartsCaisse",
    "clients",
  ],
  RESPONSABLE_DISTRIBUTION: [
    "articles",
    "stock",
    "lots",
    "vehicules",
    "chauffeurs",
    "depotsDistribution",
    "tournees",
    "preparations",
    "bonsLivraison",
    "commandes",
    "reclamations",
  ],
  CHAUFFEUR: ["articles", "chauffeurs", "tournees", "bonsLivraison"],
  COMPTABILITE_DAF: [
    "famillesFiscales",
    "famillesArticle",
    "articles",
    "stock",
    "clients",
    "factures",
    "sessionsCaisse",
    "encaissements",
    "journal",
    "anomalies",
    "exportsComptables",
    "clotures",
    "codesFiscaux",
    "coutsRetours",
    "rapports",
    "coutsMatieres",
    "coutsEnergie",
    "coutsMainOeuvre",
    "amortissements",
    "coutsStandards",
    "coutsReels",
    "mouvements",
    "decaissements",
    "ecartsCaisse",
  ],
};

export function catalogKeysForRole(profil: Profil): CatalogKey[] {
  return [...new Set([...(CATALOG_BY_ROLE[profil] ?? SHARED_CATALOG)])];
}

export function detail(path: string, id: number) {
  return `${path}${id}/`;
}

export const actions = {
  validerFiche: (id: number) => api.post<FicheTechnique>(`${endpoints.fichesTechniques}${id}/valider/`),
  convertirPlanEnOf: (id: number) => api.post<OrdreFabrication>(`${endpoints.plans}${id}/convertir_en_of/`),
  avancerOf: (id: number) => api.post<{ statut: string; of: OrdreFabrication }>(`${endpoints.ofList}${id}/avancer_statut/`),
  annulerOf: (id: number, motif: string) => api.post<OrdreFabrication>(`${endpoints.ofList}${id}/annuler/`, { motif }),
  livrerDemandeMatiere: (id: number, quantite_livree?: string | number) =>
    api.post<DemandeMatiere>(
      `${endpoints.demandesMatieres}${id}/livrer/`,
      quantite_livree !== undefined ? { quantite_livree } : {},
    ),
  approuverComplement: (id: number) =>
    api.post<DemandeComplementaire>(`${endpoints.demandesComplementaires}${id}/approuver/`),
  rejeterComplement: (id: number) =>
    api.post<DemandeComplementaire>(`${endpoints.demandesComplementaires}${id}/rejeter/`),
  approuverDemande: (id: number) => api.post<DemandeAchat>(`${endpoints.demandesAchat}${id}/approuver/`),
  rejeterDemande: (id: number) => api.post<DemandeAchat>(`${endpoints.demandesAchat}${id}/rejeter/`),
  envoyerCommandeFournisseur: (id: number) => api.post<CommandeFournisseur>(`${endpoints.commandesFournisseur}${id}/envoyer/`),
  libererLot: (id: number) => api.post<Lot>(`${endpoints.lots}${id}/liberer/`),
  bloquerLot: (id: number, motif?: string) => api.post<Lot>(`${endpoints.lots}${id}/bloquer/`, motif ? { motif } : {}),
  genererLignesFacture: (id: number) => api.post<Facture>(`${endpoints.factures}${id}/generer_lignes/`),
  utiliserAvoir: (id: number, facture: number) =>
    api.post<Avoir>(`${endpoints.avoirs}${id}/utiliser/`, { facture }),
  cloturerSession: (id: number, solde_theorique: string | undefined, solde_compte: string) =>
    api.post<{ session: SessionCaisse; avertissement?: string }>(`${endpoints.sessionsCaisse}${id}/cloturer/`, {
      ...(solde_theorique ? { solde_theorique } : {}),
      solde_compte,
    }),
  confirmerPreparation: (id: number) => api.post<PreparationLivraison>(`${endpoints.preparations}${id}/confirmer_preparation/`),
  confirmerSortie: (id: number) => api.post<PreparationLivraison>(`${endpoints.preparations}${id}/confirmer_sortie/`),
  confirmerLivraison: (id: number) => api.post<BonLivraison>(`${endpoints.bonsLivraison}${id}/confirmer_livraison/`),
  terminerReconditionnement: (id: number, quantite_reconditionnee: string | number, cout?: string | number) =>
    api.post<Reconditionnement>(`${endpoints.reconditionnements}${id}/terminer/`, {
      quantite_reconditionnee,
      ...(cout !== undefined ? { cout } : {}),
    }),
  recalculerCout: (id: number) => api.post<CoutReel>(`${endpoints.coutsReels}${id}/recalculer/`),
  genererRapport: (periode: "JOURNALIER" | "MENSUEL") =>
    api.post<RapportGenere>(`${endpoints.rapports}generer_aujourd_hui/`, { periode }),
};
