import { api, listAll } from "./client";
import type {
  Amortissement,
  AnomalieDetectee,
  Article,
  ArticleFournisseur,
  BesoinApprovisionnement,
  BesoinMatierePrevu,
  BonLivraison,
  Caisse,
  Chauffeur,
  Client,
  Cloture,
  Commande,
  CommandeFournisseur,
  CompositionFicheTechnique,
  ContratClient,
  ContratFournisseur,
  ControleQualite,
  CoutEnergie,
  CoutMatiere,
  CoutMainOeuvre,
  CoutReel,
  CoutStandard,
  DemandeAchat,
  Depot,
  DepotDistribution,
  EcartCaisse,
  Encaissement,
  EtapeProduction,
  ExportComptable,
  Facture,
  FicheConditionnement,
  FicheTechnique,
  Fournisseur,
  Inventaire,
  JournalAction,
  LigneCommande,
  LigneCommandeFournisseur,
  LigneInventaire,
  LigneReceptionAchat,
  Lot,
  MatriceDroit,
  MouvementStock,
  OrdreFabrication,
  PerteProduction,
  PlanProduction,
  PreparationLivraison,
  Profil,
  Prospect,
  ReceptionAchat,
  RetourFournisseur,
  RetourMatiere,
  SessionCaisse,
  SortieMatiere,
  StockArticle,
  Tarif,
  Tournee,
  TransfertDepot,
  Utilisateur,
  Vehicule,
} from "../types";

export const endpoints = {
  utilisateurs: "/comptes/utilisateurs/",
  droits: "/comptes/droits/",
  journal: "/comptes/journal/",
  articles: "/referentiel/articles/",
  fichesTechniques: "/referentiel/fiches-techniques/",
  compositions: "/referentiel/compositions/",
  fichesConditionnement: "/referentiel/fiches-conditionnement/",
  fournisseurs: "/achats/fournisseurs/",
  contratsFournisseurs: "/achats/contrats-fournisseurs/",
  catalogueFournisseurs: "/achats/catalogue-fournisseurs/",
  besoinsAchat: "/achats/besoins/",
  demandesAchat: "/achats/demandes/",
  commandesFournisseur: "/achats/commandes/",
  lignesCommandeFournisseur: "/achats/lignes-commande/",
  receptions: "/achats/receptions/",
  lignesReception: "/achats/lignes-reception/",
  retoursFournisseur: "/achats/retours/",
  depots: "/stocks/depots/",
  stock: "/stocks/stock-articles/",
  mouvements: "/stocks/mouvements/",
  inventaires: "/stocks/inventaires/",
  lignesInventaire: "/stocks/lignes-inventaire/",
  plans: "/production/plans/",
  ofList: "/production/ordres-fabrication/",
  besoinsMatieres: "/production/besoins-matieres/",
  sortiesMatieres: "/production/sorties-matieres/",
  retoursMatieres: "/production/retours-matieres/",
  etapes: "/production/etapes/",
  pertes: "/production/pertes/",
  lots: "/qualite/lots/",
  controles: "/qualite/controles/",
  clients: "/commercial/clients/",
  prospects: "/commercial/prospects/",
  contratsClients: "/commercial/contrats/",
  tarifs: "/commercial/tarifs/",
  commandes: "/commercial/commandes/",
  lignesCommande: "/commercial/lignes-commande/",
  factures: "/commercial/factures/",
  caisses: "/caisse/caisses/",
  sessionsCaisse: "/caisse/sessions/",
  encaissements: "/caisse/encaissements/",
  ecartsCaisse: "/caisse/ecarts/",
  vehicules: "/distribution/vehicules/",
  chauffeurs: "/distribution/chauffeurs/",
  depotsDistribution: "/distribution/depots/",
  tournees: "/distribution/tournees/",
  preparations: "/distribution/preparations/",
  bonsLivraison: "/distribution/bons-livraison/",
  transferts: "/distribution/transferts/",
  coutsMatieres: "/couts/couts-matieres/",
  coutsEnergie: "/couts/couts-energie/",
  coutsMainOeuvre: "/couts/couts-main-oeuvre/",
  amortissements: "/couts/amortissements/",
  coutsStandards: "/couts/couts-standards/",
  coutsReels: "/couts/couts-reels/",
  anomalies: "/comptabilite/anomalies/",
  exportsComptables: "/comptabilite/exports/",
  clotures: "/comptabilite/clotures/",
} as const;

export type EndpointKey = keyof typeof endpoints;

export const catalog = {
  utilisateurs: () => listAll<Utilisateur>(endpoints.utilisateurs),
  droits: () => listAll<MatriceDroit>(endpoints.droits),
  journal: () => listAll<JournalAction>(endpoints.journal),
  articles: () => listAll<Article>(endpoints.articles),
  fichesTechniques: () => listAll<FicheTechnique>(endpoints.fichesTechniques),
  compositions: () => listAll<CompositionFicheTechnique>(endpoints.compositions),
  fichesConditionnement: () => listAll<FicheConditionnement>(endpoints.fichesConditionnement),
  fournisseurs: () => listAll<Fournisseur>(endpoints.fournisseurs),
  contratsFournisseurs: () => listAll<ContratFournisseur>(endpoints.contratsFournisseurs),
  catalogueFournisseurs: () => listAll<ArticleFournisseur>(endpoints.catalogueFournisseurs),
  besoinsAchat: () => listAll<BesoinApprovisionnement>(endpoints.besoinsAchat),
  demandesAchat: () => listAll<DemandeAchat>(endpoints.demandesAchat),
  commandesFournisseur: () => listAll<CommandeFournisseur>(endpoints.commandesFournisseur),
  lignesCommandeFournisseur: () => listAll<LigneCommandeFournisseur>(endpoints.lignesCommandeFournisseur),
  receptions: () => listAll<ReceptionAchat>(endpoints.receptions),
  lignesReception: () => listAll<LigneReceptionAchat>(endpoints.lignesReception),
  retoursFournisseur: () => listAll<RetourFournisseur>(endpoints.retoursFournisseur),
  depots: () => listAll<Depot>(endpoints.depots),
  stock: () => listAll<StockArticle>(endpoints.stock),
  mouvements: () => listAll<MouvementStock>(endpoints.mouvements),
  inventaires: () => listAll<Inventaire>(endpoints.inventaires),
  lignesInventaire: () => listAll<LigneInventaire>(endpoints.lignesInventaire),
  plans: () => listAll<PlanProduction>(endpoints.plans),
  ofList: () => listAll<OrdreFabrication>(endpoints.ofList),
  besoinsMatieres: () => listAll<BesoinMatierePrevu>(endpoints.besoinsMatieres),
  sortiesMatieres: () => listAll<SortieMatiere>(endpoints.sortiesMatieres),
  retoursMatieres: () => listAll<RetourMatiere>(endpoints.retoursMatieres),
  etapes: () => listAll<EtapeProduction>(endpoints.etapes),
  pertes: () => listAll<PerteProduction>(endpoints.pertes),
  lots: () => listAll<Lot>(endpoints.lots),
  controles: () => listAll<ControleQualite>(endpoints.controles),
  clients: () => listAll<Client>(endpoints.clients),
  prospects: () => listAll<Prospect>(endpoints.prospects),
  contratsClients: () => listAll<ContratClient>(endpoints.contratsClients),
  tarifs: () => listAll<Tarif>(endpoints.tarifs),
  commandes: () => listAll<Commande>(endpoints.commandes),
  lignesCommande: () => listAll<LigneCommande>(endpoints.lignesCommande),
  factures: () => listAll<Facture>(endpoints.factures),
  caisses: () => listAll<Caisse>(endpoints.caisses),
  sessionsCaisse: () => listAll<SessionCaisse>(endpoints.sessionsCaisse),
  encaissements: () => listAll<Encaissement>(endpoints.encaissements),
  ecartsCaisse: () => listAll<EcartCaisse>(endpoints.ecartsCaisse),
  vehicules: () => listAll<Vehicule>(endpoints.vehicules),
  chauffeurs: () => listAll<Chauffeur>(endpoints.chauffeurs),
  depotsDistribution: () => listAll<DepotDistribution>(endpoints.depotsDistribution),
  tournees: () => listAll<Tournee>(endpoints.tournees),
  preparations: () => listAll<PreparationLivraison>(endpoints.preparations),
  bonsLivraison: () => listAll<BonLivraison>(endpoints.bonsLivraison),
  transferts: () => listAll<TransfertDepot>(endpoints.transferts),
  coutsMatieres: () => listAll<CoutMatiere>(endpoints.coutsMatieres),
  coutsEnergie: () => listAll<CoutEnergie>(endpoints.coutsEnergie),
  coutsMainOeuvre: () => listAll<CoutMainOeuvre>(endpoints.coutsMainOeuvre),
  amortissements: () => listAll<Amortissement>(endpoints.amortissements),
  coutsStandards: () => listAll<CoutStandard>(endpoints.coutsStandards),
  coutsReels: () => listAll<CoutReel>(endpoints.coutsReels),
  anomalies: () => listAll<AnomalieDetectee>(endpoints.anomalies),
  exportsComptables: () => listAll<ExportComptable>(endpoints.exportsComptables),
  clotures: () => listAll<Cloture>(endpoints.clotures),
};

export type CatalogKey = keyof typeof catalog;

const SHARED_CATALOG: CatalogKey[] = ["articles", "stock", "lots"];

const CATALOG_BY_ROLE: Record<Profil, CatalogKey[]> = {
  ADMIN_SI: Object.keys(catalog) as CatalogKey[],
  DIRECTION: [
    "articles",
    "stock",
    "lots",
    "journal",
    "coutsMatieres",
    "coutsEnergie",
    "coutsMainOeuvre",
    "amortissements",
    "coutsStandards",
    "coutsReels",
    "anomalies",
  ],
  RESPONSABLE_PRODUCTION: [
    "articles",
    "fichesTechniques",
    "compositions",
    "fichesConditionnement",
    "plans",
    "ofList",
    "besoinsMatieres",
    "etapes",
    "pertes",
    "stock",
    "lots",
    "depots",
    "demandesAchat",
    "besoinsAchat",
  ],
  AGENT_PRODUCTION: ["articles", "ofList", "etapes", "pertes", "stock"],
  RESPONSABLE_QUALITE: ["articles", "lots", "controles", "stock"],
  MAGASINIER: [
    "articles",
    "depots",
    "stock",
    "mouvements",
    "inventaires",
    "lignesInventaire",
    "sortiesMatieres",
    "retoursMatieres",
    "besoinsMatieres",
    "receptions",
    "lignesReception",
    "demandesAchat",
    "preparations",
    "lots",
    "transferts",
  ],
  RESPONSABLE_ACHATS: [
    "articles",
    "fournisseurs",
    "contratsFournisseurs",
    "catalogueFournisseurs",
    "besoinsAchat",
    "demandesAchat",
    "commandesFournisseur",
    "lignesCommandeFournisseur",
    "receptions",
    "lignesReception",
    "stock",
    "lots",
  ],
  COMMERCIAL: [
    "articles",
    "stock",
    "lots",
    "clients",
    "prospects",
    "contratsClients",
    "tarifs",
    "commandes",
    "lignesCommande",
    "factures",
  ],
  CAISSIER: ["articles", "commandes", "factures", "sessionsCaisse", "encaissements", "ecartsCaisse"],
  RESPONSABLE_DISTRIBUTION: [
    "articles",
    "stock",
    "lots",
    "vehicules",
    "chauffeurs",
    "depotsDistribution",
    "tournees",
    "preparations",
    "bonsLivraison",
    "commandes",
  ],
  CHAUFFEUR: ["articles", "tournees", "bonsLivraison"],
  COMPTABILITE_DAF: [
    "articles",
    "stock",
    "clients",
    "factures",
    "sessionsCaisse",
    "encaissements",
    "journal",
    "anomalies",
    "exportsComptables",
    "clotures",
    "coutsMatieres",
    "coutsEnergie",
    "coutsMainOeuvre",
    "amortissements",
    "coutsStandards",
    "coutsReels",
    "mouvements",
  ],
};

export function catalogKeysForRole(profil: Profil): CatalogKey[] {
  return [...new Set([...(CATALOG_BY_ROLE[profil] ?? SHARED_CATALOG)])];
}

export function detail(path: string, id: number) {
  return `${path}${id}/`;
}

export const actions = {
  validerFiche: (id: number) => api.post<FicheTechnique>(`${endpoints.fichesTechniques}${id}/valider/`),
  avancerOf: (id: number) => api.post<{ statut: string; of: OrdreFabrication }>(`${endpoints.ofList}${id}/avancer_statut/`),
  approuverDemande: (id: number) => api.post<DemandeAchat>(`${endpoints.demandesAchat}${id}/approuver/`),
  rejeterDemande: (id: number) => api.post<DemandeAchat>(`${endpoints.demandesAchat}${id}/rejeter/`),
  envoyerCommandeFournisseur: (id: number) => api.post<CommandeFournisseur>(`${endpoints.commandesFournisseur}${id}/envoyer/`),
  libererLot: (id: number) => api.post<Lot>(`${endpoints.lots}${id}/liberer/`),
  bloquerLot: (id: number, motif?: string) => api.post<Lot>(`${endpoints.lots}${id}/bloquer/`, motif ? { motif } : {}),
  cloturerSession: (id: number, solde_theorique: string, solde_compte: string) =>
    api.post<{ session: SessionCaisse; avertissement?: string }>(`${endpoints.sessionsCaisse}${id}/cloturer/`, {
      solde_theorique,
      solde_compte,
    }),
  confirmerPreparation: (id: number) => api.post<PreparationLivraison>(`${endpoints.preparations}${id}/confirmer_preparation/`),
  confirmerSortie: (id: number) => api.post<PreparationLivraison>(`${endpoints.preparations}${id}/confirmer_sortie/`),
  confirmerLivraison: (id: number) => api.post<BonLivraison>(`${endpoints.bonsLivraison}${id}/confirmer_livraison/`),
  recalculerCout: (id: number) => api.post<CoutReel>(`${endpoints.coutsReels}${id}/recalculer/`),
};
