import type { LucideIcon } from "lucide-react";
import {
  ArrowLeftRight,
  PencilLine,
  Binoculars,
  BookOpenText,
  Scale,
  Box,
  CalendarClock,
  CalendarDays,
  Calculator,
  ClipboardCheck,
  Contact,
  Droplets,
  FileOutput,
  FileText,
  FlaskConical,
  HandCoins,
  History,
  Inbox,
  LayoutDashboard,
  ListChecks,
  ListTodo,
  Lock,
  MessageSquareWarning,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  Percent,
  Receipt,
  Route,
  ScrollText,
  Settings2,
  Tag,
  TrendingDown,
  Undo2,
  Users,
  Vault,
  Wallet,
  Warehouse,
  Wheat,
  AlertTriangle,
  BarChart3,
  Boxes,
  CheckCircle2,
  ClipboardList,
  Coins,
  Factory,
  Handshake,
  Home,
  Package,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Truck,
  Banknote,
  Wrench,
} from "lucide-react";

export const NAV_ICONS: Record<string, LucideIcon> = {
  home: Home,
  bar: BarChart3,
  factory: Factory,
  boxes: Boxes,
  cart: ShoppingCart,
  handshake: Handshake,
  banknote: Banknote,
  truck: Truck,
  alert: AlertTriangle,
  coins: Coins,
  ledger: ClipboardList,
  sliders: SlidersHorizontal,
  shield: Shield,
  check: CheckCircle2,
  package: Package,
};

/** Icône de chaque écran du menu, par route. */
export const ITEM_ICONS: Record<string, LucideIcon> = {
  "/accueil": Home,
  "/dashboard": LayoutDashboard,
  "/production/planning": CalendarDays,
  "/production/of": ClipboardList,
  "/production/suivi": ListChecks,
  "/production/suivi-eau": Droplets,
  "/production/pertes": TrendingDown,
  "/production/qualite": FlaskConical,
  "/production/qualite/of": Inbox,
  "/production/besoins": Calculator,
  "/production/demandes-matieres": PackageMinus,
  "/stocks": Warehouse,
  "/stocks/mouvements": ArrowLeftRight,
  "/stocks/inventaires": ClipboardCheck,
  "/approvisionnement/besoins": ListTodo,
  "/approvisionnement/demandes": FileText,
  "/approvisionnement/commandes": ShoppingCart,
  "/approvisionnement/receptions": PackageCheck,
  "/commercial/commandes": ClipboardList,
  "/commercial/facturation": Receipt,
  "/commercial/clients": Users,
  "/commercial/avoirs": Undo2,
  "/commercial/impayes": CalendarClock,
  "/caisse": Receipt,
  "/caisse/cloture": Vault,
  "/caisse/decaissements": HandCoins,
  "/distribution/preparations": PackageOpen,
  "/distribution/bl": Truck,
  "/distribution/tournees": Route,
  "/couts": Coins,
  "/couts/marges": BarChart3,
  "/comptabilite/brouillards": AlertTriangle,
  "/comptabilite/export-sage": FileOutput,
  "/comptabilite/clotures": Lock,
  "/comptabilite/ecritures": BookOpenText,
  "/stocks/valorisation": Scale,
  "/reclamations": MessageSquareWarning,
  "/parametrage": SlidersHorizontal,
  "/parametrage/produits": Package,
  "/parametrage/matieres": Wheat,
  "/parametrage/conditionnements": Box,
  "/parametrage/fiches-techniques": ScrollText,
  "/parametrage/depots": Warehouse,
  "/parametrage/clients": Contact,
  "/parametrage/tarifs": Tag,
  "/parametrage/fournisseurs": Truck,
  "/parametrage/fiscalite": Percent,
  "/admin/utilisateurs": Users,
  "/admin/caisses": Vault,
  "/admin/parametres": Settings2,
  "/admin/audit": History,
};

/** Icône propre à un libellé quand deux écrans partagent la même route. */
export const LABEL_ICONS: Record<string, LucideIcon> = {
  Encaissements: Wallet,
  Supervision: Binoculars,
  Approvisionnement: ShoppingCart,
  "Mes OF": ClipboardList,
  Saisir: PencilLine,
};

export const ROLE_ICONS: Record<string, LucideIcon> = {
  shield: Shield,
  bar: BarChart3,
  factory: Factory,
  wrench: Wrench,
  check: CheckCircle2,
  boxes: Boxes,
  cart: ShoppingCart,
  handshake: Handshake,
  banknote: Banknote,
  package: Package,
  truck: Truck,
  ledger: ClipboardList,
};

export const ACCENT_CLASS: Record<string, string> = {
  navy: "bg-primary",
  teal: "bg-teal",
  amber: "bg-warning",
  green: "bg-success",
  red: "bg-danger",
  slate: "bg-slate-500",
};

export const ACCENT_SOFT: Record<string, string> = {
  navy: "bg-primary-soft text-primary",
  teal: "bg-teal-soft text-teal",
  amber: "bg-warning-soft text-warning",
  green: "bg-success-soft text-success",
  red: "bg-danger-soft text-danger",
  slate: "bg-surface-2 text-muted",
};
