import type { AppState, Profil, StockArticle } from "./types";
import { num } from "./utils";

export const ACTIONS = {
  CREATE_PLAN: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  CREATE_OF: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  AVANCER_OF: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  CREATE_ETAPE: ["AGENT_PRODUCTION", "ADMIN_SI"],
  CREATE_PERTE: ["AGENT_PRODUCTION", "ADMIN_SI"],
  CREATE_SORTIE: ["MAGASINIER", "ADMIN_SI"],
  CREATE_RETOUR_MAT: ["MAGASINIER", "ADMIN_SI"],
  VALIDER_FT: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  CREATE_FT: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  LIBERER_LOT: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  BLOQUER_LOT: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  CREATE_CONTROLE: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  CREATE_LOT: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  CREATE_COMMANDE: ["COMMERCIAL", "ADMIN_SI"],
  CREATE_FACTURE: ["COMMERCIAL", "ADMIN_SI"],
  CREATE_SESSION: ["CAISSIER", "ADMIN_SI"],
  ENCAISSER: ["CAISSIER", "ADMIN_SI"],
  CLOTURER_CAISSE: ["CAISSIER", "ADMIN_SI"],
  JUSTIFIER_ECART: ["CAISSIER", "ADMIN_SI", "COMPTABILITE_DAF"],
  CREATE_DA: ["RESPONSABLE_ACHATS", "RESPONSABLE_PRODUCTION", "MAGASINIER", "ADMIN_SI"],
  APPROUVER_DA: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  REJETER_DA: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  CREATE_CF: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  ENVOYER_CF: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  CREATE_RECEPTION: ["MAGASINIER", "RESPONSABLE_ACHATS", "ADMIN_SI"],
  CREATE_MVT: ["MAGASINIER", "ADMIN_SI"],
  CREATE_DEPOT: ["MAGASINIER", "ADMIN_SI"],
  CREATE_INVENTAIRE: ["MAGASINIER", "ADMIN_SI"],
  CLOTURER_INVENTAIRE: ["MAGASINIER", "ADMIN_SI"],
  PREP_CONFIRMER: ["MAGASINIER", "ADMIN_SI"],
  PREP_SORTIE: ["MAGASINIER", "ADMIN_SI"],
  CONFIRMER_BL: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_TOURNEE: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_PREP: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_BL: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_VEHICULE: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_CHAUFFEUR: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  RECALCULER_COUT: ["COMPTABILITE_DAF", "ADMIN_SI"],
  CREATE_EXPORT: ["COMPTABILITE_DAF", "ADMIN_SI"],
  CREATE_CLOTURE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  TRAITER_ANOMALIE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  ADMIN_USERS: ["ADMIN_SI"],
} as const;

export type ActionName = keyof typeof ACTIONS;

export function canAct(role: Profil | null, action: ActionName) {
  if (!role) return false;
  return (ACTIONS[action] as readonly Profil[]).includes(role);
}

export function stockDisponible(line: StockArticle) {
  return Math.max(0, num(line.quantite_physique) - num(line.quantite_bloquee) - num(line.quantite_reservee));
}

export function stockArticleTotal(state: AppState, articleId: number) {
  return state.stock.filter((s) => s.article === articleId).reduce((a, s) => a + stockDisponible(s), 0);
}
