import type { AppState, Profil, StockArticle } from "./types";
import { num } from "./utils";

export const ACTIONS = {
  CREATE_PLAN: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  CONVERTIR_PLAN: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  AFFECTER_AGENTS_OF: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  CREATE_OF: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  AVANCER_OF: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  ANNULER_OF: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  CREATE_ETAPE: ["AGENT_PRODUCTION", "ADMIN_SI"],
  CREATE_PERTE: ["AGENT_PRODUCTION", "ADMIN_SI"],
  CREATE_SUIVI_PROD: ["AGENT_PRODUCTION", "RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  CREATE_SUIVI_EAU: ["AGENT_PRODUCTION", "RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  DEMANDER_MATIERES_OF: ["RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  LIVRER_DEMANDE_MATIERE: ["MAGASINIER", "ADMIN_SI"],
  CREATE_COMPLEMENT: ["RESPONSABLE_PRODUCTION", "AGENT_PRODUCTION", "ADMIN_SI"],
  APPROUVER_COMPLEMENT: ["MAGASINIER", "ADMIN_SI"],
  REJETER_COMPLEMENT: ["MAGASINIER", "ADMIN_SI"],
  CREATE_SORTIE: ["MAGASINIER", "ADMIN_SI"],
  CREATE_RETOUR_MAT: ["MAGASINIER", "ADMIN_SI"],
  // Paramétrage des fiches de composition : réservé à l'Admin SI depuis la
  // dernière mise à jour backend (Production et Magasinier la consultent
  // seulement — voir FicheTechniqueViewSet).
  VALIDER_FT: ["ADMIN_SI"],
  CREATE_FT: ["ADMIN_SI"],
  LIBERER_LOT: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  BLOQUER_LOT: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  CREATE_CONTROLE: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  CREATE_LOT: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  // Admin SI : aucun accès aux commandes, factures, encaissements ni tarifs (cahier des charges).
  CREATE_COMMANDE: ["COMMERCIAL"],
  CREATE_FACTURE: ["COMMERCIAL"],
  GENERER_LIGNES_FACTURE: ["COMMERCIAL"],
  CREATE_AVOIR: ["COMMERCIAL", "COMPTABILITE_DAF", "ADMIN_SI"],
  UTILISER_AVOIR: ["COMMERCIAL", "COMPTABILITE_DAF", "ADMIN_SI"],
  CREATE_SESSION: ["CAISSIER"],
  ENCAISSER: ["CAISSIER"],
  CLOTURER_CAISSE: ["CAISSIER"],
  CREATE_DECAISSEMENT: ["CAISSIER", "COMPTABILITE_DAF", "ADMIN_SI"],
  AUTORISER_DECAISSEMENT: ["DIRECTION", "COMPTABILITE_DAF", "ADMIN_SI"],
  EFFECTUER_DECAISSEMENT: ["CAISSIER", "ADMIN_SI"],
  CREATE_DA: ["RESPONSABLE_ACHATS", "RESPONSABLE_PRODUCTION", "MAGASINIER", "ADMIN_SI"],
  // Contrairement à CREATE_DA (saisie manuelle), l'action .../creer_demande/
  // n'est ouverte en écriture qu'au Responsable Achats côté backend.
  CREER_DA_DEPUIS_BESOIN: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  APPROUVER_DA: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  REJETER_DA: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  CREATE_CF: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  ENVOYER_CF: ["RESPONSABLE_ACHATS", "ADMIN_SI"],
  CREATE_RECEPTION: ["MAGASINIER", "RESPONSABLE_ACHATS", "ADMIN_SI"],
  CREATE_MVT: ["MAGASINIER", "ADMIN_SI"],
  CREATE_DEPOT: ["MAGASINIER", "ADMIN_SI"],
  CREATE_INVENTAIRE: ["MAGASINIER", "ADMIN_SI"],
  CLOTURER_INVENTAIRE: ["MAGASINIER", "ADMIN_SI"],
  PREP_CONFIRMER: ["MAGASINIER", "ADMIN_SI"],
  PREP_SORTIE: ["MAGASINIER", "ADMIN_SI"],
  CONFIRMER_BL: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  LIVRER_BL: ["CHAUFFEUR", "RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  SIGNALER_PROBLEME_BL: ["CHAUFFEUR", "RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_TOURNEE: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_PREP: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_BL: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_VEHICULE: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_CHAUFFEUR: ["RESPONSABLE_DISTRIBUTION", "ADMIN_SI"],
  CREATE_RECLAMATION: ["RESPONSABLE_DISTRIBUTION", "COMMERCIAL", "ADMIN_SI"],
  CREATE_RETOUR_PHYSIQUE: ["MAGASINIER", "RESPONSABLE_QUALITE", "ADMIN_SI"],
  CREATE_CONTROLE_RETOUR: ["MAGASINIER", "RESPONSABLE_QUALITE", "ADMIN_SI"],
  TERMINER_RECONDITIONNEMENT: ["RESPONSABLE_PRODUCTION", "AGENT_PRODUCTION", "MAGASINIER", "ADMIN_SI"],
  CREATE_SOLUTION: ["COMMERCIAL", "ADMIN_SI"],
  RECALCULER_COUT: ["COMPTABILITE_DAF", "ADMIN_SI"],
  CREATE_EXPORT: ["COMPTABILITE_DAF", "ADMIN_SI"],
  CREATE_CLOTURE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  PATCH_COMPTE_PARAMETRE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  PATCH_SEUIL_CONTROLE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  PRENDRE_EN_CHARGE_ANOMALIE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  RESOUDRE_ANOMALIE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  IGNORER_ANOMALIE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  DETECTER_ANOMALIES: ["COMPTABILITE_DAF", "ADMIN_SI"],
  GENERER_RAPPORT: ["DIRECTION", "COMPTABILITE_DAF", "ADMIN_SI"],
  VALORISER_COUT_RETOUR: ["COMPTABILITE_DAF", "ADMIN_SI"],
  ADMIN_USERS: ["ADMIN_SI"],
  // --- Fiches techniques : essai (Admin SI, comme la validation) ---
  TESTER_FT: ["ADMIN_SI"],
  // --- Socle industriel : activités, usines, lignes, postes, machines, circuits ---
  PARAM_INDUSTRIEL: ["ADMIN_SI", "DIRECTION"],
  PARAM_PRODUCTION: ["ADMIN_SI", "DIRECTION"],
  SAISIR_CHANGEMENT_SERIE: ["RESPONSABLE_PRODUCTION", "AGENT_PRODUCTION", "ADMIN_SI"],
  // --- Référentiel : conversions d'unités ---
  GERER_CONVERSIONS: ["RESPONSABLE_PRODUCTION", "RESPONSABLE_ACHATS", "ADMIN_SI"],
  // --- Stocks : lots matières et bons de transfert ---
  GERER_LOTS_MATIERES: ["MAGASINIER", "ADMIN_SI"],
  LIBERER_LOT_MATIERE: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  GERER_TRANSFERTS: ["MAGASINIER", "ADMIN_SI"],
  // --- Contrôle qualité ---
  PARAM_QUALITE: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  SAISIR_CONTROLE: ["RESPONSABLE_QUALITE", "RESPONSABLE_PRODUCTION", "AGENT_PRODUCTION", "MAGASINIER", "ADMIN_SI"],
  CREER_CONTROLE_PONCTUEL: ["RESPONSABLE_QUALITE", "RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  REPRISE_CONTROLE: ["RESPONSABLE_QUALITE", "RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  ANNULER_CONTROLE: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  GERER_NC: ["RESPONSABLE_QUALITE", "ADMIN_SI"],
  JOINDRE_PIECE_QUALITE: ["RESPONSABLE_QUALITE", "AGENT_PRODUCTION", "ADMIN_SI"],
  VOIR_INDICATEURS_QUALITE: ["RESPONSABLE_QUALITE", "DIRECTION", "RESPONSABLE_PRODUCTION", "ADMIN_SI"],
  // --- Coûts en cascade ---
  GERER_COUTS_CASCADE: ["COMPTABILITE_DAF", "ADMIN_SI"],
  VOIR_COUTS_CASCADE: ["COMPTABILITE_DAF", "DIRECTION", "ADMIN_SI"],
  // --- Documents imprimés : identité et logo de l'entreprise ---
  PARAM_DOCUMENTS: ["ADMIN_SI", "DIRECTION", "COMPTABILITE_DAF"],
} as const;

export type ActionName = keyof typeof ACTIONS;

export function canAct(role: Profil | null, action: ActionName) {
  if (!role) return false;
  return (ACTIONS[action] as readonly Profil[]).includes(role);
}

export function stockDisponible(line: StockArticle) {
  return Math.max(0, num(line.quantite_physique) - num(line.quantite_bloquee) - num(line.quantite_reservee));
}

export function stockArticleTotal(state: AppState, articleId: number) {
  return state.stock.filter((s) => s.article === articleId).reduce((a, s) => a + stockDisponible(s), 0);
}
