import type { AppState } from "./types";

export { ROLE_LABEL } from "./roles";

export const FAMILY_LABEL = {
  eau: "Eau",
  jus: "Jus / boissons",
  yaourt: "Yaourts",
} as const;

export function seedState(): AppState {
  return {
    currentUserId: null,
    depotId: "dep-pf",
    users: [
      { id: "u-admin", name: "Amel Kaci", email: "admin@evam.dz", role: "administrateur", active: true },
      { id: "u-dir", name: "Nadir Bensalem", email: "direction@evam.dz", role: "direction", active: true },
      { id: "u-rp", name: "Soraya Mebarki", email: "production@evam.dz", role: "responsable_production", active: true },
      { id: "u-ap", name: "Karim Touati", email: "atelier@evam.dz", role: "agent_production", active: true },
      { id: "u-q", name: "Lina Cherif", email: "qualite@evam.dz", role: "controleur_qualite", active: true },
      { id: "u-m", name: "Hamid Ouali", email: "magasin@evam.dz", role: "magasinier", active: true },
      { id: "u-ra", name: "Samia Djerbi", email: "achats@evam.dz", role: "responsable_achats", active: true },
      { id: "u-c", name: "Yacine Brahimi", email: "commercial@evam.dz", role: "commercial", active: true },
      { id: "u-k", name: "Nadia Saadi", email: "caisse@evam.dz", role: "caissier", active: true },
      { id: "u-p", name: "Riad Mansouri", email: "prep@evam.dz", role: "preparateur", active: true },
      { id: "u-l", name: "Farid Meziane", email: "logistique@evam.dz", role: "logistique", active: true },
      { id: "u-cp", name: "Amina Ferhat", email: "compta@evam.dz", role: "comptabilite", active: true },
    ],
    products: [
      {
        id: "p-eau",
        code: "PF-EAU-150",
        name: "Eau minérale 1,5 L",
        family: "eau",
        unit: "bouteille",
        active: true,
        technicalSheetId: "ft-eau",
        saleUnit: "pack 6",
        minStock: 2400,
        priceHt: 85,
      },
      {
        id: "p-jus",
        code: "PF-JUS-100",
        name: "Jus d'orange 1 L",
        family: "jus",
        unit: "bouteille",
        active: true,
        technicalSheetId: "ft-jus",
        saleUnit: "pack 6",
        minStock: 800,
        priceHt: 220,
      },
      {
        id: "p-yao",
        code: "PF-YAO-125",
        name: "Yaourt nature 4 × 125 g",
        family: "yaourt",
        unit: "pot",
        active: true,
        technicalSheetId: "ft-yao",
        saleUnit: "barquette",
        minStock: 600,
        priceHt: 160,
      },
    ],
    materials: [
      { id: "m-eau-src", code: "MP-EAU", name: "Eau de source", kind: "ingredient", unit: "L", minStock: 20000, cmup: 0.4, supplierIds: ["s-src"] },
      { id: "m-sucre", code: "MP-SUC", name: "Sucre cristallisé", kind: "ingredient", unit: "kg", minStock: 800, cmup: 145, supplierIds: ["s-agro"] },
      { id: "m-conc", code: "MP-CONC", name: "Concentré orange", kind: "ingredient", unit: "kg", minStock: 200, cmup: 890, supplierIds: ["s-agro"] },
      { id: "m-lait", code: "MP-LAIT", name: "Lait pasteurisé", kind: "ingredient", unit: "L", minStock: 1500, cmup: 95, supplierIds: ["s-lait"] },
      { id: "m-fer", code: "MP-FER", name: "Ferments lactiques", kind: "additif", unit: "g", minStock: 50, cmup: 12.5, supplierIds: ["s-lait"] },
      { id: "m-bot15", code: "EMB-BOT15", name: "Bouteille PET 1,5 L", kind: "emballage", unit: "u", minStock: 5000, cmup: 18, supplierIds: ["s-emb"] },
      { id: "m-bot10", code: "EMB-BOT10", name: "Bouteille PET 1 L", kind: "emballage", unit: "u", minStock: 3000, cmup: 16, supplierIds: ["s-emb"] },
      { id: "m-pot", code: "EMB-POT", name: "Pot yaourt 125 g", kind: "emballage", unit: "u", minStock: 8000, cmup: 4.2, supplierIds: ["s-emb"] },
      { id: "m-bouch", code: "EMB-BOU", name: "Bouchon PE", kind: "emballage", unit: "u", minStock: 8000, cmup: 1.8, supplierIds: ["s-emb"] },
      { id: "m-eti", code: "EMB-ETI", name: "Étiquette EVAM", kind: "emballage", unit: "u", minStock: 10000, cmup: 0.9, supplierIds: ["s-emb"] },
    ],
    sheets: [
      {
        id: "ft-eau",
        productId: "p-eau",
        version: 3,
        status: "active",
        yieldExpected: 98,
        yieldTolerance: 2,
        composition: [{ materialId: "m-eau-src", qty: 1.52 }],
        packaging: [
          { materialId: "m-bot15", qty: 1 },
          { materialId: "m-bouch", qty: 1 },
          { materialId: "m-eti", qty: 1 },
        ],
        process: [
          { step: "Captage / filtration", durationMin: 25, instruction: "Contrôle turbidité < 0,5 NTU" },
          { step: "Ozonation", durationMin: 12, instruction: "Dose 0,4 mg/L" },
          { step: "Soutirage 1,5 L", durationMin: 40, instruction: "Ligne A — cadence 6 000 bph" },
        ],
        qualityChecks: [
          { name: "pH", min: 6.8, max: 7.4, unit: "", required: true },
          { name: "Conductivité", min: 200, max: 450, unit: "µS/cm", required: true },
          { name: "Goût / odeur", unit: "conforme", required: true },
        ],
      },
      {
        id: "ft-jus",
        productId: "p-jus",
        version: 2,
        status: "active",
        yieldExpected: 96,
        yieldTolerance: 3,
        composition: [
          { materialId: "m-eau-src", qty: 0.88 },
          { materialId: "m-conc", qty: 0.11 },
          { materialId: "m-sucre", qty: 0.04 },
        ],
        packaging: [
          { materialId: "m-bot10", qty: 1 },
          { materialId: "m-bouch", qty: 1 },
          { materialId: "m-eti", qty: 1 },
        ],
        process: [
          { step: "Reconstitution", durationMin: 30, instruction: "Brix cible 11,2" },
          { step: "Pasteurisation", durationMin: 18, instruction: "85 °C / 15 s" },
          { step: "Remplissage à chaud", durationMin: 35, instruction: "Ligne B" },
        ],
        qualityChecks: [
          { name: "Brix", min: 10.8, max: 11.6, unit: "°Brix", required: true },
          { name: "pH", min: 3.2, max: 3.8, unit: "", required: true },
          { name: "Étanchéité", unit: "ok", required: true },
        ],
      },
      {
        id: "ft-yao",
        productId: "p-yao",
        version: 4,
        status: "active",
        yieldExpected: 97,
        yieldTolerance: 2,
        composition: [
          { materialId: "m-lait", qty: 0.5 },
          { materialId: "m-fer", qty: 0.4 },
        ],
        packaging: [{ materialId: "m-pot", qty: 4 }],
        process: [
          { step: "Standardisation", durationMin: 20, instruction: "Matière grasse 3,2 %" },
          { step: "Ensemencement", durationMin: 15, instruction: "42 °C" },
          { step: "Incubation", durationMin: 240, instruction: "Jusqu'à pH 4,6" },
          { step: "Refroidissement", durationMin: 90, instruction: "4 °C" },
        ],
        qualityChecks: [
          { name: "pH", min: 4.4, max: 4.7, unit: "", required: true },
          { name: "Texture", unit: "ferme", required: true },
          { name: "Flore pathogène", unit: "absence", required: true },
        ],
      },
    ],
    depots: [
      { id: "dep-pf", code: "PF-01", name: "Produits finis", kind: "pf" },
      { id: "dep-mp", code: "MP-01", name: "Matières premières", kind: "matieres" },
      { id: "dep-q", code: "QUA-01", name: "Quarantaine", kind: "quarantaine" },
      { id: "dep-ret", code: "RET-01", name: "Retours", kind: "retours" },
    ],
    stock: [
      { id: "st-1", articleId: "p-eau", articleType: "produit", depotId: "dep-pf", lot: "L-EAU-0821", qty: 4200, reserved: 360, cmup: 62.4 },
      { id: "st-2", articleId: "p-jus", articleType: "produit", depotId: "dep-pf", lot: "L-JUS-0818", qty: 960, reserved: 120, cmup: 148.2 },
      { id: "st-3", articleId: "p-yao", articleType: "produit", depotId: "dep-pf", lot: "L-YAO-0819", qty: 180, reserved: 0, cmup: 92.1 },
      { id: "st-4", articleId: "m-eau-src", articleType: "matiere", depotId: "dep-mp", qty: 18500, reserved: 0, cmup: 0.4 },
      { id: "st-5", articleId: "m-sucre", articleType: "matiere", depotId: "dep-mp", qty: 620, reserved: 40, cmup: 145 },
      { id: "st-6", articleId: "m-conc", articleType: "matiere", depotId: "dep-mp", qty: 140, reserved: 0, cmup: 890 },
      { id: "st-7", articleId: "m-lait", articleType: "matiere", depotId: "dep-mp", qty: 920, reserved: 200, cmup: 95 },
      { id: "st-8", articleId: "m-bot15", articleType: "matiere", depotId: "dep-mp", qty: 6400, reserved: 0, cmup: 18 },
      { id: "st-9", articleId: "m-bot10", articleType: "matiere", depotId: "dep-mp", qty: 2100, reserved: 0, cmup: 16 },
      { id: "st-10", articleId: "m-pot", articleType: "matiere", depotId: "dep-mp", qty: 9200, reserved: 0, cmup: 4.2 },
      { id: "st-11", articleId: "m-bouch", articleType: "matiere", depotId: "dep-mp", qty: 11000, reserved: 0, cmup: 1.8 },
      { id: "st-12", articleId: "m-eti", articleType: "matiere", depotId: "dep-mp", qty: 15000, reserved: 0, cmup: 0.9 },
      { id: "st-13", articleId: "m-fer", articleType: "matiere", depotId: "dep-mp", qty: 38, reserved: 0, cmup: 12.5 },
    ],
    plans: [
      { id: "pl-1", productId: "p-eau", date: "2026-08-19", qty: 6000, ofId: "OF-2026-00041" },
      { id: "pl-2", productId: "p-yao", date: "2026-08-19", qty: 2000, ofId: "OF-2026-00042" },
      { id: "pl-3", productId: "p-jus", date: "2026-08-20", qty: 3000, ofId: "OF-2026-00043" },
    ],
    ofList: [
      {
        id: "OF-2026-00041",
        planId: "pl-1",
        productId: "p-eau",
        qtyPlanned: 6000,
        qtyReal: 5880,
        status: "en_production",
        lot: "L-EAU-0822",
        createdAt: "2026-08-19T06:00:00",
        waterVolumeM3: 9.1,
      },
      {
        id: "OF-2026-00042",
        planId: "pl-2",
        productId: "p-yao",
        qtyPlanned: 2000,
        qtyReal: 2000,
        status: "fin_production",
        lot: "L-YAO-0822",
        createdAt: "2026-08-19T05:30:00",
        yieldActual: 97.4,
        qualityResult: "en_attente",
      },
      {
        id: "OF-2026-00043",
        planId: "pl-3",
        productId: "p-jus",
        qtyPlanned: 3000,
        qtyReal: 0,
        status: "planifie",
        createdAt: "2026-08-19T08:00:00",
      },
      {
        id: "OF-2026-00038",
        planId: "pl-x",
        productId: "p-eau",
        qtyPlanned: 5000,
        qtyReal: 4920,
        status: "cloture",
        lot: "L-EAU-0821",
        createdAt: "2026-08-18T06:00:00",
        yieldActual: 98.4,
        cost: 306988,
        qualityResult: "conforme",
        waterVolumeM3: 7.6,
      },
      {
        id: "OF-2026-00039",
        planId: "pl-y",
        productId: "p-jus",
        qtyPlanned: 1500,
        qtyReal: 1410,
        status: "bloque",
        lot: "L-JUS-0820",
        createdAt: "2026-08-18T07:00:00",
        yieldActual: 94,
        qualityResult: "non_conforme",
        qualityNotes: "Brix 10,2 — hors tolérance. Lot en quarantaine.",
      },
    ],
    materialRequests: [
      {
        id: "dm-1",
        ofId: "OF-2026-00041",
        status: "servie",
        lines: [
          { materialId: "m-eau-src", qty: 9120 },
          { materialId: "m-bot15", qty: 6000 },
          { materialId: "m-bouch", qty: 6000 },
          { materialId: "m-eti", qty: 6000 },
        ],
      },
      {
        id: "dm-2",
        ofId: "OF-2026-00043",
        status: "demandee",
        lines: [
          { materialId: "m-eau-src", qty: 2640 },
          { materialId: "m-conc", qty: 330 },
          { materialId: "m-sucre", qty: 120 },
          { materialId: "m-bot10", qty: 3000 },
        ],
      },
    ],
    losses: [
      { id: "loss-1", ofId: "OF-2026-00041", causeId: "c-casse", qty: 48, lot: "L-EAU-0822" },
      { id: "loss-2", ofId: "OF-2026-00039", causeId: "c-qual", qty: 90, lot: "L-JUS-0820" },
    ],
    lossCauses: [
      { id: "c-casse", label: "Casse ligne" },
      { id: "c-qual", label: "Non-conformité process" },
      { id: "c-net", label: "Pertes nettoyage" },
      { id: "c-exp", label: "Démarrage / réglage" },
    ],
    customers: [
      { id: "cl-1", code: "CL-001", name: "Superette Atlas", type: "comptant", paymentMethods: ["especes", "cb"], tariffId: "t-std" },
      { id: "cl-2", code: "CL-002", name: "Grossiste Oran Distribution", type: "a_terme", paymentMethods: ["virement"], tariffId: "t-gros" },
      { id: "cl-3", code: "CL-003", name: "Café des Palmiers", type: "comptant", paymentMethods: ["especes"], tariffId: "t-std" },
      { id: "cl-4", code: "CL-004", name: "Hôtel El Djazaïr", type: "a_terme", paymentMethods: ["virement", "cb"], tariffId: "t-horeca" },
    ],
    suppliers: [
      { id: "s-src", code: "FR-01", name: "Source des Beni", delayDays: 1 },
      { id: "s-agro", code: "FR-02", name: "AgroMaghreb Ingredients", delayDays: 7 },
      { id: "s-lait", code: "FR-03", name: "Laiterie du Tell", delayDays: 2 },
      { id: "s-emb", code: "FR-04", name: "PackMed Emballages", delayDays: 10 },
    ],
    orders: [
      {
        id: "so-1",
        number: "CD-2026-01102",
        customerId: "cl-1",
        status: "a_payer",
        lines: [{ productId: "p-eau", qty: 120, unitPrice: 85 }],
        createdAt: "2026-08-19T09:12:00",
        invoiceId: "fa-1",
        prepStatus: "a_preparer",
      },
      {
        id: "so-2",
        number: "CD-2026-01103",
        customerId: "cl-2",
        status: "payee",
        lines: [
          { productId: "p-eau", qty: 240, unitPrice: 78 },
          { productId: "p-jus", qty: 120, unitPrice: 205 },
        ],
        createdAt: "2026-08-19T09:40:00",
        invoiceId: "fa-2",
        prepStatus: "complete",
        paidAt: "2026-08-19T10:02:00",
      },
      {
        id: "so-3",
        number: "CD-2026-01104",
        customerId: "cl-3",
        status: "suspendue",
        lines: [{ productId: "p-jus", qty: 24, unitPrice: 220 }],
        createdAt: "2026-08-19T10:15:00",
        invoiceId: "fa-3",
        prepStatus: "a_preparer",
        suspendReason: "Paiement CB refusé",
      },
      {
        id: "so-4",
        number: "CD-2026-01100",
        customerId: "cl-4",
        status: "livree",
        lines: [{ productId: "p-eau", qty: 360, unitPrice: 80 }],
        createdAt: "2026-08-18T16:00:00",
        invoiceId: "fa-4",
        prepStatus: "complete",
        paidAt: "2026-08-18T16:20:00",
      },
    ],
    invoices: [
      { id: "fa-1", number: "FA-2026-01102", orderId: "so-1", amount: 10200, status: "a_payer", exported: false },
      { id: "fa-2", number: "FA-2026-01103", orderId: "so-2", amount: 43320, status: "payee", exported: false },
      { id: "fa-3", number: "FA-2026-01104", orderId: "so-3", amount: 5280, status: "suspendue", suspendReason: "Paiement CB refusé", exported: false },
      { id: "fa-4", number: "FA-2026-01100", orderId: "so-4", amount: 28800, status: "payee", exported: true },
    ],
    payments: [
      { id: "pay-2", invoiceId: "fa-2", method: "virement", amount: 43320, success: true, at: "2026-08-19T10:02:00" },
      { id: "pay-3", invoiceId: "fa-3", method: "cb", amount: 5280, success: false, at: "2026-08-19T10:16:00" },
      { id: "pay-4", invoiceId: "fa-4", method: "virement", amount: 28800, success: true, at: "2026-08-18T16:20:00" },
    ],
    deliveryNotes: [
      { id: "bl-2", number: "BL-2026-01088", orderId: "so-2", status: "valide", signed: false, proof: false },
      { id: "bl-4", number: "BL-2026-01080", orderId: "so-4", status: "livre", signed: true, proof: true },
      { id: "bl-1", number: "BL-2026-01089", orderId: "so-1", status: "verrouille", signed: false },
    ],
    purchaseRequests: [
      { id: "da-1", number: "DA-2026-00412", status: "soumise", materialId: "m-lait", qty: 800, reason: "Seuil min atteint + besoin OF yaourt" },
      { id: "da-2", number: "DA-2026-00413", status: "validee", materialId: "m-conc", qty: 250, reason: "Alerte seuil concentré orange" },
    ],
    purchaseOrders: [
      {
        id: "cf-1",
        number: "CF-2026-00188",
        supplierId: "s-lait",
        daId: "da-1",
        status: "envoyee",
        lines: [{ materialId: "m-lait", qty: 800 }],
      },
      {
        id: "cf-2",
        number: "CF-2026-00186",
        supplierId: "s-agro",
        daId: "da-2",
        status: "partielle",
        lines: [{ materialId: "m-conc", qty: 250 }],
      },
    ],
    receptions: [
      {
        id: "rc-1",
        number: "RC-2026-00077",
        poId: "cf-2",
        status: "ecart",
        lines: [{ materialId: "m-conc", ordered: 250, received: 180 }],
      },
    ],
    inventories: [
      {
        id: "inv-1",
        depotId: "dep-pf",
        status: "ouvert",
        date: "2026-08-19",
        lines: [
          { articleId: "p-eau", theoretical: 4200 },
          { articleId: "p-jus", theoretical: 960 },
          { articleId: "p-yao", theoretical: 180 },
        ],
      },
    ],
    movements: [
      { id: "mv-1", type: "entree", articleId: "p-eau", articleType: "produit", qty: 4920, depotId: "dep-pf", lot: "L-EAU-0821", origin: "Clôture OF-2026-00038", cmup: 62.4, at: "2026-08-18T15:10:00" },
      { id: "mv-2", type: "sortie", articleId: "p-eau", articleType: "produit", qty: 360, depotId: "dep-pf", lot: "L-EAU-0821", origin: "Préparation CD-2026-01100", cmup: 62.4, at: "2026-08-18T16:05:00" },
      { id: "mv-3", type: "sortie", articleId: "m-lait", articleType: "matiere", qty: 1000, depotId: "dep-mp", origin: "Demande matières OF-2026-00042", cmup: 95, at: "2026-08-19T05:40:00" },
      { id: "mv-4", type: "transfert", articleId: "p-jus", articleType: "produit", qty: 1410, depotId: "dep-pf", destDepotId: "dep-q", lot: "L-JUS-0820", origin: "Blocage qualité OF-2026-00039", cmup: 148.2, at: "2026-08-18T14:22:00" },
    ],
    claims: [
      {
        id: "re-1",
        number: "RE-2026-00014",
        orderId: "so-4",
        lot: "L-EAU-0821",
        motifId: "mot-casse",
        status: "ouverte",
        notes: "12 bouteilles cassées à la livraison — palettes mal calées.",
      },
    ],
    drafts: [
      { id: "br-1", kind: "vente", ref: "FA-2026-01100", amount: 28800, status: "exporte", journal: "VT" },
      { id: "br-2", kind: "vente", ref: "FA-2026-01103", amount: 43320, status: "a_valider", journal: "VT" },
      { id: "br-3", kind: "achat", ref: "CF-2026-00186", amount: 160200, status: "a_valider", journal: "AC" },
      { id: "br-4", kind: "vente", ref: "FA-2026-01104", amount: 5280, status: "exclu", journal: "VT" },
    ],
    audit: [
      { id: "au-1", at: "2026-08-18T15:10:00", user: "Lina Cherif", action: "Clôture qualité OF-2026-00038 — lot L-EAU-0821 entré en stock PF" },
      { id: "au-2", at: "2026-08-18T16:20:00", user: "Nadia Saadi", action: "Encaissement FA-2026-01100 — virement 28 800 DA" },
      { id: "au-3", at: "2026-08-19T10:16:00", user: "Nadia Saadi", action: "Facture FA-2026-01104 suspendue — CB refusée. Stock libéré." },
    ],
    cashSession: { open: true, theoretical: 10200 },
    settings: {
      company: "EVAM — Unité de production",
      exercice: "2026",
      ofPrefix: "OF-2026-",
      faPrefix: "FA-2026-",
      blPrefix: "BL-2026-",
      counters: { of: 43, fa: 1104, bl: 1089, da: 413 },
    },
    suspendReasons: [
      { id: "sr-cb", label: "Paiement CB refusé" },
      { id: "sr-imp", label: "Impayé / provision insuffisante" },
      { id: "sr-client", label: "Annulation client" },
    ],
    claimReasons: [
      { id: "mot-qual", label: "Qualité produit" },
      { id: "mot-casse", label: "Casse / transport" },
      { id: "mot-qty", label: "Écart de quantité" },
      { id: "mot-delai", label: "Délai de livraison" },
    ],
    sageMapping: {
      journalVente: "VT",
      journalAchat: "AC",
      compteClient: "411000",
      compteFournisseur: "401000",
    },
  };
}
